name: axe

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g http-server
      - run: npm run build --if-present
      - run: http-server -s &
      - name: Install specific version of ChromeDriver
        run: npm install -g chromedriver@125
      - name: Run axe
        id: axe-test
        run: |
          npm install -g @axe-core/cli
          sleep 90
          axe http://127.0.0.1:8080 --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --exit || echo "status=warning" >> $GITHUB_ENV
      
      - name: Set output status to warning (if test fails)
        if: env.status == 'warning'
        run: echo "::warning::Accessibility tests failed, but this does not block (most) PRs."
